[book]
authors = ["Leonardo Espejo"]
language = "es"
multilingual = false
src = "src"
title = "Lenguajes de Programacion y Metodos de Traduccion I"

[output.html]
default-theme = "Rust"
preferred-dark-theme = "Ayu"
git-repository-url = "https://github.com/Leo-Spj/mdBook-TLPMT1"
edit-url-template = "https://github.com/Leo-Spj/mdBook-TLPMT1/fork"